- name: Set benchmark to use Memory
  ansible.builtin.set_fact:
    benchmark: benchmark_ultimate_memory.json.j2
  when: ultimate_benchmark_memory | bool

- name: Set benchmark to use CPU
  ansible.builtin.set_fact:
    benchmark: benchmark_ultimate_cpu.json.j2
  when: ultimate_benchmark_cpu | bool

- name: Upload Benchmark
  ansible.builtin.uri:
    url: 'https://{{ item }}-hyperfoil.{{ route_subdomain }}/benchmark'
    url_password: openshift
    url_username: '{{ item }}'
    force_basic_auth: true
    validate_certs: false
    method: POST
    body_format: json
    headers:
      Content-Type: "application/json"
    body: "{{ lookup('template', '{{ benchmark }}') }}"
    status_code: 200,201,204
  register: r_benchmark
  retries: 5
  delay: 10
  until: r_benchmark.status in [200, 201, 204]
  loop: '{{ users }}'

- name: Start Benchmark
  ansible.builtin.uri:
    url: 'https://{{ item }}-hyperfoil.{{ route_subdomain }}/benchmark/summit-lab-load-apps/start'
    url_password: openshift
    url_username: '{{ item }}'
    force_basic_auth: true
    validate_certs: false
    method: GET
    body_format: json
    headers:
      Content-Type: "application/json"
    body: "{{ lookup('template', 'benchmark.json.j2') }}"
    status_code: 200,201,202,204
  register: r_benchmark
  retries: 5
  delay: 10
  until: r_benchmark.status in [200, 201,202, 204]
  loop: '{{ users }}'
